name: whatsapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  camera:
  http: ^0.12.0+4
  bubble: ^1.1.9+1
  font_awesome_flutter: ^8.7.0
  cupertino_icons: ^0.1.2
  story_view: ^0.12.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

